// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: nodeum/plugins/v1/dispatcher.proto

package pluginsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DispatcherPluginServiceClient is the client API for DispatcherPluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DispatcherPluginServiceClient interface {
	// Before the task is started, you can change the task and/or the trigger metadata
	OnStartNewTask(ctx context.Context, in *OnStartNewTaskRequest, opts ...grpc.CallOption) (*OnStartNewTaskResponse, error)
	// Before a request is dispatched, you can change it or discard it
	OnNewRequest(ctx context.Context, in *OnNewRequestRequest, opts ...grpc.CallOption) (*OnNewRequestResponse, error)
}

type dispatcherPluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDispatcherPluginServiceClient(cc grpc.ClientConnInterface) DispatcherPluginServiceClient {
	return &dispatcherPluginServiceClient{cc}
}

func (c *dispatcherPluginServiceClient) OnStartNewTask(ctx context.Context, in *OnStartNewTaskRequest, opts ...grpc.CallOption) (*OnStartNewTaskResponse, error) {
	out := new(OnStartNewTaskResponse)
	err := c.cc.Invoke(ctx, "/nodeum.plugins.v1.DispatcherPluginService/OnStartNewTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatcherPluginServiceClient) OnNewRequest(ctx context.Context, in *OnNewRequestRequest, opts ...grpc.CallOption) (*OnNewRequestResponse, error) {
	out := new(OnNewRequestResponse)
	err := c.cc.Invoke(ctx, "/nodeum.plugins.v1.DispatcherPluginService/OnNewRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DispatcherPluginServiceServer is the server API for DispatcherPluginService service.
// All implementations must embed UnimplementedDispatcherPluginServiceServer
// for forward compatibility
type DispatcherPluginServiceServer interface {
	// Before the task is started, you can change the task and/or the trigger metadata
	OnStartNewTask(context.Context, *OnStartNewTaskRequest) (*OnStartNewTaskResponse, error)
	// Before a request is dispatched, you can change it or discard it
	OnNewRequest(context.Context, *OnNewRequestRequest) (*OnNewRequestResponse, error)
	mustEmbedUnimplementedDispatcherPluginServiceServer()
}

// UnimplementedDispatcherPluginServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDispatcherPluginServiceServer struct {
}

func (UnimplementedDispatcherPluginServiceServer) OnStartNewTask(context.Context, *OnStartNewTaskRequest) (*OnStartNewTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnStartNewTask not implemented")
}
func (UnimplementedDispatcherPluginServiceServer) OnNewRequest(context.Context, *OnNewRequestRequest) (*OnNewRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnNewRequest not implemented")
}
func (UnimplementedDispatcherPluginServiceServer) mustEmbedUnimplementedDispatcherPluginServiceServer() {
}

// UnsafeDispatcherPluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DispatcherPluginServiceServer will
// result in compilation errors.
type UnsafeDispatcherPluginServiceServer interface {
	mustEmbedUnimplementedDispatcherPluginServiceServer()
}

func RegisterDispatcherPluginServiceServer(s grpc.ServiceRegistrar, srv DispatcherPluginServiceServer) {
	s.RegisterService(&DispatcherPluginService_ServiceDesc, srv)
}

func _DispatcherPluginService_OnStartNewTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnStartNewTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatcherPluginServiceServer).OnStartNewTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodeum.plugins.v1.DispatcherPluginService/OnStartNewTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatcherPluginServiceServer).OnStartNewTask(ctx, req.(*OnStartNewTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DispatcherPluginService_OnNewRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnNewRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatcherPluginServiceServer).OnNewRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodeum.plugins.v1.DispatcherPluginService/OnNewRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatcherPluginServiceServer).OnNewRequest(ctx, req.(*OnNewRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DispatcherPluginService_ServiceDesc is the grpc.ServiceDesc for DispatcherPluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DispatcherPluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nodeum.plugins.v1.DispatcherPluginService",
	HandlerType: (*DispatcherPluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnStartNewTask",
			Handler:    _DispatcherPluginService_OnStartNewTask_Handler,
		},
		{
			MethodName: "OnNewRequest",
			Handler:    _DispatcherPluginService_OnNewRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nodeum/plugins/v1/dispatcher.proto",
}
