// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: nodeum/plugins/v1/dispatcher.proto

package pluginsv1

import (
	fmt "fmt"
	_ "github.com/nodeum-io/nodeum-proto/nodeum/common/v1"
	proto "google.golang.org/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/structpb"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for DispatcherPluginService service

func NewDispatcherPluginServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for DispatcherPluginService service

type DispatcherPluginService interface {
	// Before the task is started, you can change the task and/or the trigger metadata
	BeforeTaskExecuted(ctx context.Context, in *BeforeTaskExecutedRequest, opts ...client.CallOption) (*BeforeTaskExecutedResponse, error)
	// Before a request is dispatched, you can change it or discard it
	BeforeRequestDispatched(ctx context.Context, in *BeforeRequestDispatchedRequest, opts ...client.CallOption) (*BeforeRequestDispatchedResponse, error)
	// After a result has been received and before it's being handled by finalizer.
	// Progress results are excluded.
	AfterResultReceived(ctx context.Context, in *AfterResultReceivedRequest, opts ...client.CallOption) (*AfterResultReceivedResponse, error)
	// After the task has been executed
	AfterTaskExecuted(ctx context.Context, in *AfterTaskExecutedRequest, opts ...client.CallOption) (*AfterTaskExecutedResponse, error)
}

type dispatcherPluginService struct {
	c    client.Client
	name string
}

func NewDispatcherPluginService(name string, c client.Client) DispatcherPluginService {
	return &dispatcherPluginService{
		c:    c,
		name: name,
	}
}

func (c *dispatcherPluginService) BeforeTaskExecuted(ctx context.Context, in *BeforeTaskExecutedRequest, opts ...client.CallOption) (*BeforeTaskExecutedResponse, error) {
	req := c.c.NewRequest(c.name, "DispatcherPluginService.BeforeTaskExecuted", in)
	out := new(BeforeTaskExecutedResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatcherPluginService) BeforeRequestDispatched(ctx context.Context, in *BeforeRequestDispatchedRequest, opts ...client.CallOption) (*BeforeRequestDispatchedResponse, error) {
	req := c.c.NewRequest(c.name, "DispatcherPluginService.BeforeRequestDispatched", in)
	out := new(BeforeRequestDispatchedResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatcherPluginService) AfterResultReceived(ctx context.Context, in *AfterResultReceivedRequest, opts ...client.CallOption) (*AfterResultReceivedResponse, error) {
	req := c.c.NewRequest(c.name, "DispatcherPluginService.AfterResultReceived", in)
	out := new(AfterResultReceivedResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatcherPluginService) AfterTaskExecuted(ctx context.Context, in *AfterTaskExecutedRequest, opts ...client.CallOption) (*AfterTaskExecutedResponse, error) {
	req := c.c.NewRequest(c.name, "DispatcherPluginService.AfterTaskExecuted", in)
	out := new(AfterTaskExecutedResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DispatcherPluginService service

type DispatcherPluginServiceHandler interface {
	// Before the task is started, you can change the task and/or the trigger metadata
	BeforeTaskExecuted(context.Context, *BeforeTaskExecutedRequest, *BeforeTaskExecutedResponse) error
	// Before a request is dispatched, you can change it or discard it
	BeforeRequestDispatched(context.Context, *BeforeRequestDispatchedRequest, *BeforeRequestDispatchedResponse) error
	// After a result has been received and before it's being handled by finalizer.
	// Progress results are excluded.
	AfterResultReceived(context.Context, *AfterResultReceivedRequest, *AfterResultReceivedResponse) error
	// After the task has been executed
	AfterTaskExecuted(context.Context, *AfterTaskExecutedRequest, *AfterTaskExecutedResponse) error
}

func RegisterDispatcherPluginServiceHandler(s server.Server, hdlr DispatcherPluginServiceHandler, opts ...server.HandlerOption) error {
	type dispatcherPluginService interface {
		BeforeTaskExecuted(ctx context.Context, in *BeforeTaskExecutedRequest, out *BeforeTaskExecutedResponse) error
		BeforeRequestDispatched(ctx context.Context, in *BeforeRequestDispatchedRequest, out *BeforeRequestDispatchedResponse) error
		AfterResultReceived(ctx context.Context, in *AfterResultReceivedRequest, out *AfterResultReceivedResponse) error
		AfterTaskExecuted(ctx context.Context, in *AfterTaskExecutedRequest, out *AfterTaskExecutedResponse) error
	}
	type DispatcherPluginService struct {
		dispatcherPluginService
	}
	h := &dispatcherPluginServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&DispatcherPluginService{h}, opts...))
}

type dispatcherPluginServiceHandler struct {
	DispatcherPluginServiceHandler
}

func (h *dispatcherPluginServiceHandler) BeforeTaskExecuted(ctx context.Context, in *BeforeTaskExecutedRequest, out *BeforeTaskExecutedResponse) error {
	return h.DispatcherPluginServiceHandler.BeforeTaskExecuted(ctx, in, out)
}

func (h *dispatcherPluginServiceHandler) BeforeRequestDispatched(ctx context.Context, in *BeforeRequestDispatchedRequest, out *BeforeRequestDispatchedResponse) error {
	return h.DispatcherPluginServiceHandler.BeforeRequestDispatched(ctx, in, out)
}

func (h *dispatcherPluginServiceHandler) AfterResultReceived(ctx context.Context, in *AfterResultReceivedRequest, out *AfterResultReceivedResponse) error {
	return h.DispatcherPluginServiceHandler.AfterResultReceived(ctx, in, out)
}

func (h *dispatcherPluginServiceHandler) AfterTaskExecuted(ctx context.Context, in *AfterTaskExecutedRequest, out *AfterTaskExecutedResponse) error {
	return h.DispatcherPluginServiceHandler.AfterTaskExecuted(ctx, in, out)
}
