// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: nodeum/plugins/v1/finalizer.proto

package pluginsv1

import (
	v1 "github.com/nodeum-io/nodeum-proto/nodeum/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AfterResultReceivedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Execution *v1.Execution `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"`
	Result    *v1.Result    `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *AfterResultReceivedRequest) Reset() {
	*x = AfterResultReceivedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeum_plugins_v1_finalizer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AfterResultReceivedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AfterResultReceivedRequest) ProtoMessage() {}

func (x *AfterResultReceivedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeum_plugins_v1_finalizer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AfterResultReceivedRequest.ProtoReflect.Descriptor instead.
func (*AfterResultReceivedRequest) Descriptor() ([]byte, []int) {
	return file_nodeum_plugins_v1_finalizer_proto_rawDescGZIP(), []int{0}
}

func (x *AfterResultReceivedRequest) GetExecution() *v1.Execution {
	if x != nil {
		return x.Execution
	}
	return nil
}

func (x *AfterResultReceivedRequest) GetResult() *v1.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type AfterResultReceivedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AfterResultReceivedResponse) Reset() {
	*x = AfterResultReceivedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeum_plugins_v1_finalizer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AfterResultReceivedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AfterResultReceivedResponse) ProtoMessage() {}

func (x *AfterResultReceivedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeum_plugins_v1_finalizer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AfterResultReceivedResponse.ProtoReflect.Descriptor instead.
func (*AfterResultReceivedResponse) Descriptor() ([]byte, []int) {
	return file_nodeum_plugins_v1_finalizer_proto_rawDescGZIP(), []int{1}
}

type AfterTaskExecutedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Execution *v1.Execution `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"`
}

func (x *AfterTaskExecutedRequest) Reset() {
	*x = AfterTaskExecutedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeum_plugins_v1_finalizer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AfterTaskExecutedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AfterTaskExecutedRequest) ProtoMessage() {}

func (x *AfterTaskExecutedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeum_plugins_v1_finalizer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AfterTaskExecutedRequest.ProtoReflect.Descriptor instead.
func (*AfterTaskExecutedRequest) Descriptor() ([]byte, []int) {
	return file_nodeum_plugins_v1_finalizer_proto_rawDescGZIP(), []int{2}
}

func (x *AfterTaskExecutedRequest) GetExecution() *v1.Execution {
	if x != nil {
		return x.Execution
	}
	return nil
}

type AfterTaskExecutedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AfterTaskExecutedResponse) Reset() {
	*x = AfterTaskExecutedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeum_plugins_v1_finalizer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AfterTaskExecutedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AfterTaskExecutedResponse) ProtoMessage() {}

func (x *AfterTaskExecutedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeum_plugins_v1_finalizer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AfterTaskExecutedResponse.ProtoReflect.Descriptor instead.
func (*AfterTaskExecutedResponse) Descriptor() ([]byte, []int) {
	return file_nodeum_plugins_v1_finalizer_proto_rawDescGZIP(), []int{3}
}

var File_nodeum_plugins_v1_finalizer_proto protoreflect.FileDescriptor

var file_nodeum_plugins_v1_finalizer_proto_rawDesc = []byte{
	0x0a, 0x21, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73,
	0x2f, 0x76, 0x31, 0x2f, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x11, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1d, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x89, 0x01, 0x0a, 0x1a, 0x41, 0x66, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x39, 0x0a, 0x09, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x09, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6e,
	0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x1d,
	0x0a, 0x1b, 0x41, 0x66, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x55, 0x0a,
	0x18, 0x41, 0x66, 0x74, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x09, 0x65, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6e,
	0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x65, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x1b, 0x0a, 0x19, 0x41, 0x66, 0x74, 0x65, 0x72, 0x54, 0x61, 0x73,
	0x6b, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0xfe, 0x01, 0x0a, 0x16, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x50,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x74, 0x0a, 0x13,
	0x41, 0x66, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x64, 0x12, 0x2d, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x66, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x66, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x6e, 0x0a, 0x11, 0x41, 0x66, 0x74, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x45,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x64, 0x12, 0x2b, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d,
	0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x66, 0x74, 0x65,
	0x72, 0x54, 0x61, 0x73, 0x6b, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x66, 0x74, 0x65, 0x72, 0x54, 0x61,
	0x73, 0x6b, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2d, 0x69, 0x6f, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x75,
	0x6d, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2f, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x73, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nodeum_plugins_v1_finalizer_proto_rawDescOnce sync.Once
	file_nodeum_plugins_v1_finalizer_proto_rawDescData = file_nodeum_plugins_v1_finalizer_proto_rawDesc
)

func file_nodeum_plugins_v1_finalizer_proto_rawDescGZIP() []byte {
	file_nodeum_plugins_v1_finalizer_proto_rawDescOnce.Do(func() {
		file_nodeum_plugins_v1_finalizer_proto_rawDescData = protoimpl.X.CompressGZIP(file_nodeum_plugins_v1_finalizer_proto_rawDescData)
	})
	return file_nodeum_plugins_v1_finalizer_proto_rawDescData
}

var file_nodeum_plugins_v1_finalizer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_nodeum_plugins_v1_finalizer_proto_goTypes = []interface{}{
	(*AfterResultReceivedRequest)(nil),  // 0: nodeum.plugins.v1.AfterResultReceivedRequest
	(*AfterResultReceivedResponse)(nil), // 1: nodeum.plugins.v1.AfterResultReceivedResponse
	(*AfterTaskExecutedRequest)(nil),    // 2: nodeum.plugins.v1.AfterTaskExecutedRequest
	(*AfterTaskExecutedResponse)(nil),   // 3: nodeum.plugins.v1.AfterTaskExecutedResponse
	(*v1.Execution)(nil),                // 4: nodeum.common.v1.Execution
	(*v1.Result)(nil),                   // 5: nodeum.common.v1.Result
}
var file_nodeum_plugins_v1_finalizer_proto_depIdxs = []int32{
	4, // 0: nodeum.plugins.v1.AfterResultReceivedRequest.execution:type_name -> nodeum.common.v1.Execution
	5, // 1: nodeum.plugins.v1.AfterResultReceivedRequest.result:type_name -> nodeum.common.v1.Result
	4, // 2: nodeum.plugins.v1.AfterTaskExecutedRequest.execution:type_name -> nodeum.common.v1.Execution
	0, // 3: nodeum.plugins.v1.FinalizerPluginService.AfterResultReceived:input_type -> nodeum.plugins.v1.AfterResultReceivedRequest
	2, // 4: nodeum.plugins.v1.FinalizerPluginService.AfterTaskExecuted:input_type -> nodeum.plugins.v1.AfterTaskExecutedRequest
	1, // 5: nodeum.plugins.v1.FinalizerPluginService.AfterResultReceived:output_type -> nodeum.plugins.v1.AfterResultReceivedResponse
	3, // 6: nodeum.plugins.v1.FinalizerPluginService.AfterTaskExecuted:output_type -> nodeum.plugins.v1.AfterTaskExecutedResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_nodeum_plugins_v1_finalizer_proto_init() }
func file_nodeum_plugins_v1_finalizer_proto_init() {
	if File_nodeum_plugins_v1_finalizer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nodeum_plugins_v1_finalizer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AfterResultReceivedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeum_plugins_v1_finalizer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AfterResultReceivedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeum_plugins_v1_finalizer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AfterTaskExecutedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeum_plugins_v1_finalizer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AfterTaskExecutedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nodeum_plugins_v1_finalizer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nodeum_plugins_v1_finalizer_proto_goTypes,
		DependencyIndexes: file_nodeum_plugins_v1_finalizer_proto_depIdxs,
		MessageInfos:      file_nodeum_plugins_v1_finalizer_proto_msgTypes,
	}.Build()
	File_nodeum_plugins_v1_finalizer_proto = out.File
	file_nodeum_plugins_v1_finalizer_proto_rawDesc = nil
	file_nodeum_plugins_v1_finalizer_proto_goTypes = nil
	file_nodeum_plugins_v1_finalizer_proto_depIdxs = nil
}
