// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: protobuf/finalizer.micro.proto

package finalizerpb

import (
	fmt "fmt"
	_ "github.com/nodeum-io/nodeum-plugins/protobuf/types/storagespb"
	_ "github.com/nodeum-io/nodeum-plugins/protobuf/types/taskpb"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Finalizer service

func NewFinalizerEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Finalizer service

type FinalizerService interface {
	Start(ctx context.Context, in *StartRequest, opts ...client.CallOption) (*StartResponse, error)
}

type finalizerService struct {
	c    client.Client
	name string
}

func NewFinalizerService(name string, c client.Client) FinalizerService {
	return &finalizerService{
		c:    c,
		name: name,
	}
}

func (c *finalizerService) Start(ctx context.Context, in *StartRequest, opts ...client.CallOption) (*StartResponse, error) {
	req := c.c.NewRequest(c.name, "Finalizer.Start", in)
	out := new(StartResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Finalizer service

type FinalizerHandler interface {
	Start(context.Context, *StartRequest, *StartResponse) error
}

func RegisterFinalizerHandler(s server.Server, hdlr FinalizerHandler, opts ...server.HandlerOption) error {
	type finalizer interface {
		Start(ctx context.Context, in *StartRequest, out *StartResponse) error
	}
	type Finalizer struct {
		finalizer
	}
	h := &finalizerHandler{hdlr}
	return s.Handle(s.NewHandler(&Finalizer{h}, opts...))
}

type finalizerHandler struct {
	FinalizerHandler
}

func (h *finalizerHandler) Start(ctx context.Context, in *StartRequest, out *StartResponse) error {
	return h.FinalizerHandler.Start(ctx, in, out)
}
