// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: nodeum/common/v1/version.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Secondary_Type int32

const (
	Secondary_TYPE_UNSPECIFIED Secondary_Type = 0
	Secondary_TYPE_TAPE        Secondary_Type = 1
	Secondary_TYPE_CLOUD       Secondary_Type = 2
	Secondary_TYPE_NAS         Secondary_Type = 3
)

// Enum value maps for Secondary_Type.
var (
	Secondary_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_TAPE",
		2: "TYPE_CLOUD",
		3: "TYPE_NAS",
	}
	Secondary_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_TAPE":        1,
		"TYPE_CLOUD":       2,
		"TYPE_NAS":         3,
	}
)

func (x Secondary_Type) Enum() *Secondary_Type {
	p := new(Secondary_Type)
	*p = x
	return p
}

func (x Secondary_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Secondary_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_nodeum_common_v1_version_proto_enumTypes[0].Descriptor()
}

func (Secondary_Type) Type() protoreflect.EnumType {
	return &file_nodeum_common_v1_version_proto_enumTypes[0]
}

func (x Secondary_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Secondary_Type.Descriptor instead.
func (Secondary_Type) EnumDescriptor() ([]byte, []int) {
	return file_nodeum_common_v1_version_proto_rawDescGZIP(), []int{2, 0}
}

type Version struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Info *NodeInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	// Types that are assignable to Type:
	//
	//	*Version_Primary
	//	*Version_Secondary
	Type isVersion_Type `protobuf_oneof:"type"`
}

func (x *Version) Reset() {
	*x = Version{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeum_common_v1_version_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_nodeum_common_v1_version_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_nodeum_common_v1_version_proto_rawDescGZIP(), []int{0}
}

func (x *Version) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Version) GetInfo() *NodeInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (m *Version) GetType() isVersion_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Version) GetPrimary() *Primary {
	if x, ok := x.GetType().(*Version_Primary); ok {
		return x.Primary
	}
	return nil
}

func (x *Version) GetSecondary() *Secondary {
	if x, ok := x.GetType().(*Version_Secondary); ok {
		return x.Secondary
	}
	return nil
}

type isVersion_Type interface {
	isVersion_Type()
}

type Version_Primary struct {
	Primary *Primary `protobuf:"bytes,3,opt,name=primary,proto3,oneof"`
}

type Version_Secondary struct {
	Secondary *Secondary `protobuf:"bytes,4,opt,name=secondary,proto3,oneof"`
}

func (*Version_Primary) isVersion_Type() {}

func (*Version_Secondary) isVersion_Type() {}

type Primary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Primary) Reset() {
	*x = Primary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeum_common_v1_version_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Primary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Primary) ProtoMessage() {}

func (x *Primary) ProtoReflect() protoreflect.Message {
	mi := &file_nodeum_common_v1_version_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Primary.ProtoReflect.Descriptor instead.
func (*Primary) Descriptor() ([]byte, []int) {
	return file_nodeum_common_v1_version_proto_rawDescGZIP(), []int{1}
}

type Secondary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      Secondary_Type `protobuf:"varint,1,opt,name=type,proto3,enum=nodeum.common.v1.Secondary_Type" json:"type,omitempty"`
	StorageId uint64         `protobuf:"varint,2,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	Path      string         `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *Secondary) Reset() {
	*x = Secondary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeum_common_v1_version_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Secondary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secondary) ProtoMessage() {}

func (x *Secondary) ProtoReflect() protoreflect.Message {
	mi := &file_nodeum_common_v1_version_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secondary.ProtoReflect.Descriptor instead.
func (*Secondary) Descriptor() ([]byte, []int) {
	return file_nodeum_common_v1_version_proto_rawDescGZIP(), []int{2}
}

func (x *Secondary) GetType() Secondary_Type {
	if x != nil {
		return x.Type
	}
	return Secondary_TYPE_UNSPECIFIED
}

func (x *Secondary) GetStorageId() uint64 {
	if x != nil {
		return x.StorageId
	}
	return 0
}

func (x *Secondary) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_nodeum_common_v1_version_proto protoreflect.FileDescriptor

var file_nodeum_common_v1_version_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x76, 0x31, 0x2f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x10, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x76, 0x31, 0x1a, 0x1f, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xc5, 0x01, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x2e, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12,
	0x35, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x48, 0x00, 0x52, 0x07, 0x70,
	0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x3b, 0x0a, 0x09, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x61, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6e, 0x6f, 0x64, 0x65,
	0x75, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x48, 0x00, 0x52, 0x09, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x61, 0x72, 0x79, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x09, 0x0a, 0x07, 0x50,
	0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x22, 0xbf, 0x01, 0x0a, 0x09, 0x53, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x61, 0x72, 0x79, 0x12, 0x34, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x20, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x2e,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x49, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x54, 0x41, 0x50, 0x45, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x43, 0x4c, 0x4f, 0x55, 0x44, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x4e, 0x41, 0x53, 0x10, 0x03, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2d, 0x69, 0x6f,
	0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x6f,
	0x64, 0x65, 0x75, 0x6d, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nodeum_common_v1_version_proto_rawDescOnce sync.Once
	file_nodeum_common_v1_version_proto_rawDescData = file_nodeum_common_v1_version_proto_rawDesc
)

func file_nodeum_common_v1_version_proto_rawDescGZIP() []byte {
	file_nodeum_common_v1_version_proto_rawDescOnce.Do(func() {
		file_nodeum_common_v1_version_proto_rawDescData = protoimpl.X.CompressGZIP(file_nodeum_common_v1_version_proto_rawDescData)
	})
	return file_nodeum_common_v1_version_proto_rawDescData
}

var file_nodeum_common_v1_version_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nodeum_common_v1_version_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nodeum_common_v1_version_proto_goTypes = []interface{}{
	(Secondary_Type)(0), // 0: nodeum.common.v1.Secondary.Type
	(*Version)(nil),     // 1: nodeum.common.v1.Version
	(*Primary)(nil),     // 2: nodeum.common.v1.Primary
	(*Secondary)(nil),   // 3: nodeum.common.v1.Secondary
	(*NodeInfo)(nil),    // 4: nodeum.common.v1.NodeInfo
}
var file_nodeum_common_v1_version_proto_depIdxs = []int32{
	4, // 0: nodeum.common.v1.Version.info:type_name -> nodeum.common.v1.NodeInfo
	2, // 1: nodeum.common.v1.Version.primary:type_name -> nodeum.common.v1.Primary
	3, // 2: nodeum.common.v1.Version.secondary:type_name -> nodeum.common.v1.Secondary
	0, // 3: nodeum.common.v1.Secondary.type:type_name -> nodeum.common.v1.Secondary.Type
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_nodeum_common_v1_version_proto_init() }
func file_nodeum_common_v1_version_proto_init() {
	if File_nodeum_common_v1_version_proto != nil {
		return
	}
	file_nodeum_common_v1_nodeinfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_nodeum_common_v1_version_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Version); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeum_common_v1_version_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Primary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeum_common_v1_version_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Secondary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_nodeum_common_v1_version_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Version_Primary)(nil),
		(*Version_Secondary)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nodeum_common_v1_version_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nodeum_common_v1_version_proto_goTypes,
		DependencyIndexes: file_nodeum_common_v1_version_proto_depIdxs,
		EnumInfos:         file_nodeum_common_v1_version_proto_enumTypes,
		MessageInfos:      file_nodeum_common_v1_version_proto_msgTypes,
	}.Build()
	File_nodeum_common_v1_version_proto = out.File
	file_nodeum_common_v1_version_proto_rawDesc = nil
	file_nodeum_common_v1_version_proto_goTypes = nil
	file_nodeum_common_v1_version_proto_depIdxs = nil
}
