// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: nodeum/micro/v1/finalizer.proto

package microv1

import (
	v1 "github.com/nodeum-io/nodeum-proto/nodeum/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FinalizerServiceStartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkflowId  string        `protobuf:"bytes,1,opt,name=workflow_id,proto3" json:"workflow_id,omitempty"`
	Execution   *v1.Execution `protobuf:"bytes,4,opt,name=execution,proto3" json:"execution,omitempty"`
	Source      *v1.Storage   `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Destination *v1.Storage   `protobuf:"bytes,6,opt,name=destination,proto3" json:"destination,omitempty"`
}

func (x *FinalizerServiceStartRequest) Reset() {
	*x = FinalizerServiceStartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeum_micro_v1_finalizer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinalizerServiceStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizerServiceStartRequest) ProtoMessage() {}

func (x *FinalizerServiceStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeum_micro_v1_finalizer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizerServiceStartRequest.ProtoReflect.Descriptor instead.
func (*FinalizerServiceStartRequest) Descriptor() ([]byte, []int) {
	return file_nodeum_micro_v1_finalizer_proto_rawDescGZIP(), []int{0}
}

func (x *FinalizerServiceStartRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *FinalizerServiceStartRequest) GetExecution() *v1.Execution {
	if x != nil {
		return x.Execution
	}
	return nil
}

func (x *FinalizerServiceStartRequest) GetSource() *v1.Storage {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *FinalizerServiceStartRequest) GetDestination() *v1.Storage {
	if x != nil {
		return x.Destination
	}
	return nil
}

type FinalizerServiceStartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FinalizerServiceStartResponse) Reset() {
	*x = FinalizerServiceStartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeum_micro_v1_finalizer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinalizerServiceStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizerServiceStartResponse) ProtoMessage() {}

func (x *FinalizerServiceStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeum_micro_v1_finalizer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizerServiceStartResponse.ProtoReflect.Descriptor instead.
func (*FinalizerServiceStartResponse) Descriptor() ([]byte, []int) {
	return file_nodeum_micro_v1_finalizer_proto_rawDescGZIP(), []int{1}
}

type FinalizerServicePauseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FinalizerServicePauseRequest) Reset() {
	*x = FinalizerServicePauseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeum_micro_v1_finalizer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinalizerServicePauseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizerServicePauseRequest) ProtoMessage() {}

func (x *FinalizerServicePauseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeum_micro_v1_finalizer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizerServicePauseRequest.ProtoReflect.Descriptor instead.
func (*FinalizerServicePauseRequest) Descriptor() ([]byte, []int) {
	return file_nodeum_micro_v1_finalizer_proto_rawDescGZIP(), []int{2}
}

func (x *FinalizerServicePauseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FinalizerServicePauseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *FinalizerServicePauseResponse) Reset() {
	*x = FinalizerServicePauseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeum_micro_v1_finalizer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinalizerServicePauseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizerServicePauseResponse) ProtoMessage() {}

func (x *FinalizerServicePauseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeum_micro_v1_finalizer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizerServicePauseResponse.ProtoReflect.Descriptor instead.
func (*FinalizerServicePauseResponse) Descriptor() ([]byte, []int) {
	return file_nodeum_micro_v1_finalizer_proto_rawDescGZIP(), []int{3}
}

func (x *FinalizerServicePauseResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type FinalizerServiceResumeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FinalizerServiceResumeRequest) Reset() {
	*x = FinalizerServiceResumeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeum_micro_v1_finalizer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinalizerServiceResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizerServiceResumeRequest) ProtoMessage() {}

func (x *FinalizerServiceResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeum_micro_v1_finalizer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizerServiceResumeRequest.ProtoReflect.Descriptor instead.
func (*FinalizerServiceResumeRequest) Descriptor() ([]byte, []int) {
	return file_nodeum_micro_v1_finalizer_proto_rawDescGZIP(), []int{4}
}

func (x *FinalizerServiceResumeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FinalizerServiceResumeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *FinalizerServiceResumeResponse) Reset() {
	*x = FinalizerServiceResumeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeum_micro_v1_finalizer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinalizerServiceResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizerServiceResumeResponse) ProtoMessage() {}

func (x *FinalizerServiceResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeum_micro_v1_finalizer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizerServiceResumeResponse.ProtoReflect.Descriptor instead.
func (*FinalizerServiceResumeResponse) Descriptor() ([]byte, []int) {
	return file_nodeum_micro_v1_finalizer_proto_rawDescGZIP(), []int{5}
}

func (x *FinalizerServiceResumeResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type FinalizerServiceStopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FinalizerServiceStopRequest) Reset() {
	*x = FinalizerServiceStopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeum_micro_v1_finalizer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinalizerServiceStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizerServiceStopRequest) ProtoMessage() {}

func (x *FinalizerServiceStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeum_micro_v1_finalizer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizerServiceStopRequest.ProtoReflect.Descriptor instead.
func (*FinalizerServiceStopRequest) Descriptor() ([]byte, []int) {
	return file_nodeum_micro_v1_finalizer_proto_rawDescGZIP(), []int{6}
}

func (x *FinalizerServiceStopRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FinalizerServiceStopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *FinalizerServiceStopResponse) Reset() {
	*x = FinalizerServiceStopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeum_micro_v1_finalizer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinalizerServiceStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizerServiceStopResponse) ProtoMessage() {}

func (x *FinalizerServiceStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeum_micro_v1_finalizer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizerServiceStopResponse.ProtoReflect.Descriptor instead.
func (*FinalizerServiceStopResponse) Descriptor() ([]byte, []int) {
	return file_nodeum_micro_v1_finalizer_proto_rawDescGZIP(), []int{7}
}

func (x *FinalizerServiceStopResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_nodeum_micro_v1_finalizer_proto protoreflect.FileDescriptor

var file_nodeum_micro_v1_finalizer_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2f, 0x76,
	0x31, 0x2f, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0f, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e,
	0x76, 0x31, 0x1a, 0x1f, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xeb, 0x01, 0x0a, 0x1c, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x20, 0x0a, 0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77,
	0x5f, 0x69, 0x64, 0x12, 0x39, 0x0a, 0x09, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x09, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x31,
	0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x1f,
	0x0a, 0x1d, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x2e, 0x0a, 0x1c, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x50, 0x61, 0x75, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x31, 0x0a, 0x1d, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x50, 0x61, 0x75, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x22, 0x2f, 0x0a, 0x1d, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x32, 0x0a, 0x1e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x2d, 0x0a, 0x1b, 0x46, 0x69, 0x6e, 0x61, 0x6c,
	0x69, 0x7a, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x6f, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x30, 0x0a, 0x1c, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69,
	0x7a, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0xb8, 0x03, 0x0a, 0x10, 0x46, 0x69, 0x6e,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x66, 0x0a,
	0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x2d, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e,
	0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x6d,
	0x69, 0x63, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x68, 0x0a, 0x05, 0x50, 0x61, 0x75, 0x73, 0x65, 0x12, 0x2d,
	0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x76, 0x31,
	0x2e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x50, 0x61, 0x75, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e,
	0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x50, 0x61, 0x75, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x6b, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x12, 0x2e, 0x2e, 0x6e, 0x6f, 0x64, 0x65,
	0x75, 0x6d, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x61,
	0x6c, 0x69, 0x7a, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x6e, 0x6f, 0x64, 0x65,
	0x75, 0x6d, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x61,
	0x6c, 0x69, 0x7a, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x65, 0x0a, 0x04,
	0x53, 0x74, 0x6f, 0x70, 0x12, 0x2c, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x6d, 0x69,
	0x63, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x6d, 0x69, 0x63, 0x72,
	0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2d, 0x69, 0x6f, 0x2f, 0x6e, 0x6f, 0x64, 0x65,
	0x75, 0x6d, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2f,
	0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2f, 0x76, 0x31, 0x3b, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nodeum_micro_v1_finalizer_proto_rawDescOnce sync.Once
	file_nodeum_micro_v1_finalizer_proto_rawDescData = file_nodeum_micro_v1_finalizer_proto_rawDesc
)

func file_nodeum_micro_v1_finalizer_proto_rawDescGZIP() []byte {
	file_nodeum_micro_v1_finalizer_proto_rawDescOnce.Do(func() {
		file_nodeum_micro_v1_finalizer_proto_rawDescData = protoimpl.X.CompressGZIP(file_nodeum_micro_v1_finalizer_proto_rawDescData)
	})
	return file_nodeum_micro_v1_finalizer_proto_rawDescData
}

var file_nodeum_micro_v1_finalizer_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_nodeum_micro_v1_finalizer_proto_goTypes = []interface{}{
	(*FinalizerServiceStartRequest)(nil),   // 0: nodeum.micro.v1.FinalizerServiceStartRequest
	(*FinalizerServiceStartResponse)(nil),  // 1: nodeum.micro.v1.FinalizerServiceStartResponse
	(*FinalizerServicePauseRequest)(nil),   // 2: nodeum.micro.v1.FinalizerServicePauseRequest
	(*FinalizerServicePauseResponse)(nil),  // 3: nodeum.micro.v1.FinalizerServicePauseResponse
	(*FinalizerServiceResumeRequest)(nil),  // 4: nodeum.micro.v1.FinalizerServiceResumeRequest
	(*FinalizerServiceResumeResponse)(nil), // 5: nodeum.micro.v1.FinalizerServiceResumeResponse
	(*FinalizerServiceStopRequest)(nil),    // 6: nodeum.micro.v1.FinalizerServiceStopRequest
	(*FinalizerServiceStopResponse)(nil),   // 7: nodeum.micro.v1.FinalizerServiceStopResponse
	(*v1.Execution)(nil),                   // 8: nodeum.common.v1.Execution
	(*v1.Storage)(nil),                     // 9: nodeum.common.v1.Storage
}
var file_nodeum_micro_v1_finalizer_proto_depIdxs = []int32{
	8, // 0: nodeum.micro.v1.FinalizerServiceStartRequest.execution:type_name -> nodeum.common.v1.Execution
	9, // 1: nodeum.micro.v1.FinalizerServiceStartRequest.source:type_name -> nodeum.common.v1.Storage
	9, // 2: nodeum.micro.v1.FinalizerServiceStartRequest.destination:type_name -> nodeum.common.v1.Storage
	0, // 3: nodeum.micro.v1.FinalizerService.Start:input_type -> nodeum.micro.v1.FinalizerServiceStartRequest
	2, // 4: nodeum.micro.v1.FinalizerService.Pause:input_type -> nodeum.micro.v1.FinalizerServicePauseRequest
	4, // 5: nodeum.micro.v1.FinalizerService.Resume:input_type -> nodeum.micro.v1.FinalizerServiceResumeRequest
	6, // 6: nodeum.micro.v1.FinalizerService.Stop:input_type -> nodeum.micro.v1.FinalizerServiceStopRequest
	1, // 7: nodeum.micro.v1.FinalizerService.Start:output_type -> nodeum.micro.v1.FinalizerServiceStartResponse
	3, // 8: nodeum.micro.v1.FinalizerService.Pause:output_type -> nodeum.micro.v1.FinalizerServicePauseResponse
	5, // 9: nodeum.micro.v1.FinalizerService.Resume:output_type -> nodeum.micro.v1.FinalizerServiceResumeResponse
	7, // 10: nodeum.micro.v1.FinalizerService.Stop:output_type -> nodeum.micro.v1.FinalizerServiceStopResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_nodeum_micro_v1_finalizer_proto_init() }
func file_nodeum_micro_v1_finalizer_proto_init() {
	if File_nodeum_micro_v1_finalizer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nodeum_micro_v1_finalizer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinalizerServiceStartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeum_micro_v1_finalizer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinalizerServiceStartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeum_micro_v1_finalizer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinalizerServicePauseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeum_micro_v1_finalizer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinalizerServicePauseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeum_micro_v1_finalizer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinalizerServiceResumeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeum_micro_v1_finalizer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinalizerServiceResumeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeum_micro_v1_finalizer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinalizerServiceStopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeum_micro_v1_finalizer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinalizerServiceStopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nodeum_micro_v1_finalizer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nodeum_micro_v1_finalizer_proto_goTypes,
		DependencyIndexes: file_nodeum_micro_v1_finalizer_proto_depIdxs,
		MessageInfos:      file_nodeum_micro_v1_finalizer_proto_msgTypes,
	}.Build()
	File_nodeum_micro_v1_finalizer_proto = out.File
	file_nodeum_micro_v1_finalizer_proto_rawDesc = nil
	file_nodeum_micro_v1_finalizer_proto_goTypes = nil
	file_nodeum_micro_v1_finalizer_proto_depIdxs = nil
}
