// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: nodeum/micro/v1/monitoring.proto

package microv1

import (
	fmt "fmt"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	proto "google.golang.org/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for DebugService service

func NewDebugServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for DebugService service

type DebugService interface {
	Info(ctx context.Context, in *InfoRequest, opts ...client.CallOption) (*InfoResponse, error)
	Stats(ctx context.Context, in *StatsRequest, opts ...client.CallOption) (*StatsResponse, error)
}

type debugService struct {
	c    client.Client
	name string
}

func NewDebugService(name string, c client.Client) DebugService {
	return &debugService{
		c:    c,
		name: name,
	}
}

func (c *debugService) Info(ctx context.Context, in *InfoRequest, opts ...client.CallOption) (*InfoResponse, error) {
	req := c.c.NewRequest(c.name, "DebugService.Info", in)
	out := new(InfoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugService) Stats(ctx context.Context, in *StatsRequest, opts ...client.CallOption) (*StatsResponse, error) {
	req := c.c.NewRequest(c.name, "DebugService.Stats", in)
	out := new(StatsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DebugService service

type DebugServiceHandler interface {
	Info(context.Context, *InfoRequest, *InfoResponse) error
	Stats(context.Context, *StatsRequest, *StatsResponse) error
}

func RegisterDebugServiceHandler(s server.Server, hdlr DebugServiceHandler, opts ...server.HandlerOption) error {
	type debugService interface {
		Info(ctx context.Context, in *InfoRequest, out *InfoResponse) error
		Stats(ctx context.Context, in *StatsRequest, out *StatsResponse) error
	}
	type DebugService struct {
		debugService
	}
	h := &debugServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&DebugService{h}, opts...))
}

type debugServiceHandler struct {
	DebugServiceHandler
}

func (h *debugServiceHandler) Info(ctx context.Context, in *InfoRequest, out *InfoResponse) error {
	return h.DebugServiceHandler.Info(ctx, in, out)
}

func (h *debugServiceHandler) Stats(ctx context.Context, in *StatsRequest, out *StatsResponse) error {
	return h.DebugServiceHandler.Stats(ctx, in, out)
}

// Api Endpoints for MonitoringService service

func NewMonitoringServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{
		{
			Name:    "MonitoringService.ListServices",
			Path:    []string{"/services"},
			Method:  []string{"GET"},
			Handler: "rpc",
		},
		{
			Name:    "MonitoringService.ListHosts",
			Path:    []string{"/hosts"},
			Method:  []string{"GET"},
			Handler: "rpc",
		},
	}
}

// Client API for MonitoringService service

type MonitoringService interface {
	// ListServices returns all registered services.
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...client.CallOption) (*ListServicesResponse, error)
	// ListHosts returns information about hosts running services.
	ListHosts(ctx context.Context, in *ListHostsRequest, opts ...client.CallOption) (*ListHostsResponse, error)
}

type monitoringService struct {
	c    client.Client
	name string
}

func NewMonitoringService(name string, c client.Client) MonitoringService {
	return &monitoringService{
		c:    c,
		name: name,
	}
}

func (c *monitoringService) ListServices(ctx context.Context, in *ListServicesRequest, opts ...client.CallOption) (*ListServicesResponse, error) {
	req := c.c.NewRequest(c.name, "MonitoringService.ListServices", in)
	out := new(ListServicesResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitoringService) ListHosts(ctx context.Context, in *ListHostsRequest, opts ...client.CallOption) (*ListHostsResponse, error) {
	req := c.c.NewRequest(c.name, "MonitoringService.ListHosts", in)
	out := new(ListHostsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MonitoringService service

type MonitoringServiceHandler interface {
	// ListServices returns all registered services.
	ListServices(context.Context, *ListServicesRequest, *ListServicesResponse) error
	// ListHosts returns information about hosts running services.
	ListHosts(context.Context, *ListHostsRequest, *ListHostsResponse) error
}

func RegisterMonitoringServiceHandler(s server.Server, hdlr MonitoringServiceHandler, opts ...server.HandlerOption) error {
	type monitoringService interface {
		ListServices(ctx context.Context, in *ListServicesRequest, out *ListServicesResponse) error
		ListHosts(ctx context.Context, in *ListHostsRequest, out *ListHostsResponse) error
	}
	type MonitoringService struct {
		monitoringService
	}
	h := &monitoringServiceHandler{hdlr}
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "MonitoringService.ListServices",
		Path:    []string{"/services"},
		Method:  []string{"GET"},
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "MonitoringService.ListHosts",
		Path:    []string{"/hosts"},
		Method:  []string{"GET"},
		Handler: "rpc",
	}))
	return s.Handle(s.NewHandler(&MonitoringService{h}, opts...))
}

type monitoringServiceHandler struct {
	MonitoringServiceHandler
}

func (h *monitoringServiceHandler) ListServices(ctx context.Context, in *ListServicesRequest, out *ListServicesResponse) error {
	return h.MonitoringServiceHandler.ListServices(ctx, in, out)
}

func (h *monitoringServiceHandler) ListHosts(ctx context.Context, in *ListHostsRequest, out *ListHostsResponse) error {
	return h.MonitoringServiceHandler.ListHosts(ctx, in, out)
}
