// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: nodeum/micro/v1/mover.proto

package microv1

import (
	fmt "fmt"
	_ "github.com/nodeum-io/nodeum-proto/nodeum/common/v1"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for MoverService service

func NewMoverServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for MoverService service

type MoverService interface {
	// Pauses an execution
	Pause(ctx context.Context, in *MoverServicePauseRequest, opts ...client.CallOption) (*MoverServicePauseResponse, error)
	// Resumes a paused execution
	Resume(ctx context.Context, in *MoverServiceResumeRequest, opts ...client.CallOption) (*MoverServiceResumeResponse, error)
	// Stops an execution
	Stop(ctx context.Context, in *MoverServiceStopRequest, opts ...client.CallOption) (*MoverServiceStopResponse, error)
	// Executes one request on the mover, receives many results
	Request(ctx context.Context, in *MoverServiceRequestRequest, opts ...client.CallOption) (MoverService_RequestService, error)
	// Executes many requests on the mover, receives many results
	Requests(ctx context.Context, opts ...client.CallOption) (MoverService_RequestsService, error)
}

type moverService struct {
	c    client.Client
	name string
}

func NewMoverService(name string, c client.Client) MoverService {
	return &moverService{
		c:    c,
		name: name,
	}
}

func (c *moverService) Pause(ctx context.Context, in *MoverServicePauseRequest, opts ...client.CallOption) (*MoverServicePauseResponse, error) {
	req := c.c.NewRequest(c.name, "MoverService.Pause", in)
	out := new(MoverServicePauseResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moverService) Resume(ctx context.Context, in *MoverServiceResumeRequest, opts ...client.CallOption) (*MoverServiceResumeResponse, error) {
	req := c.c.NewRequest(c.name, "MoverService.Resume", in)
	out := new(MoverServiceResumeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moverService) Stop(ctx context.Context, in *MoverServiceStopRequest, opts ...client.CallOption) (*MoverServiceStopResponse, error) {
	req := c.c.NewRequest(c.name, "MoverService.Stop", in)
	out := new(MoverServiceStopResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moverService) Request(ctx context.Context, in *MoverServiceRequestRequest, opts ...client.CallOption) (MoverService_RequestService, error) {
	req := c.c.NewRequest(c.name, "MoverService.Request", &MoverServiceRequestRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &moverServiceRequest{stream}, nil
}

type MoverService_RequestService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*MoverServiceRequestResponse, error)
}

type moverServiceRequest struct {
	stream client.Stream
}

func (x *moverServiceRequest) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *moverServiceRequest) Close() error {
	return x.stream.Close()
}

func (x *moverServiceRequest) Context() context.Context {
	return x.stream.Context()
}

func (x *moverServiceRequest) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *moverServiceRequest) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *moverServiceRequest) Recv() (*MoverServiceRequestResponse, error) {
	m := new(MoverServiceRequestResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *moverService) Requests(ctx context.Context, opts ...client.CallOption) (MoverService_RequestsService, error) {
	req := c.c.NewRequest(c.name, "MoverService.Requests", &MoverServiceRequestsRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &moverServiceRequests{stream}, nil
}

type MoverService_RequestsService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*MoverServiceRequestsRequest) error
	Recv() (*MoverServiceRequestsResponse, error)
}

type moverServiceRequests struct {
	stream client.Stream
}

func (x *moverServiceRequests) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *moverServiceRequests) Close() error {
	return x.stream.Close()
}

func (x *moverServiceRequests) Context() context.Context {
	return x.stream.Context()
}

func (x *moverServiceRequests) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *moverServiceRequests) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *moverServiceRequests) Send(m *MoverServiceRequestsRequest) error {
	return x.stream.Send(m)
}

func (x *moverServiceRequests) Recv() (*MoverServiceRequestsResponse, error) {
	m := new(MoverServiceRequestsResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for MoverService service

type MoverServiceHandler interface {
	// Pauses an execution
	Pause(context.Context, *MoverServicePauseRequest, *MoverServicePauseResponse) error
	// Resumes a paused execution
	Resume(context.Context, *MoverServiceResumeRequest, *MoverServiceResumeResponse) error
	// Stops an execution
	Stop(context.Context, *MoverServiceStopRequest, *MoverServiceStopResponse) error
	// Executes one request on the mover, receives many results
	Request(context.Context, *MoverServiceRequestRequest, MoverService_RequestStream) error
	// Executes many requests on the mover, receives many results
	Requests(context.Context, MoverService_RequestsStream) error
}

func RegisterMoverServiceHandler(s server.Server, hdlr MoverServiceHandler, opts ...server.HandlerOption) error {
	type moverService interface {
		Pause(ctx context.Context, in *MoverServicePauseRequest, out *MoverServicePauseResponse) error
		Resume(ctx context.Context, in *MoverServiceResumeRequest, out *MoverServiceResumeResponse) error
		Stop(ctx context.Context, in *MoverServiceStopRequest, out *MoverServiceStopResponse) error
		Request(ctx context.Context, stream server.Stream) error
		Requests(ctx context.Context, stream server.Stream) error
	}
	type MoverService struct {
		moverService
	}
	h := &moverServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&MoverService{h}, opts...))
}

type moverServiceHandler struct {
	MoverServiceHandler
}

func (h *moverServiceHandler) Pause(ctx context.Context, in *MoverServicePauseRequest, out *MoverServicePauseResponse) error {
	return h.MoverServiceHandler.Pause(ctx, in, out)
}

func (h *moverServiceHandler) Resume(ctx context.Context, in *MoverServiceResumeRequest, out *MoverServiceResumeResponse) error {
	return h.MoverServiceHandler.Resume(ctx, in, out)
}

func (h *moverServiceHandler) Stop(ctx context.Context, in *MoverServiceStopRequest, out *MoverServiceStopResponse) error {
	return h.MoverServiceHandler.Stop(ctx, in, out)
}

func (h *moverServiceHandler) Request(ctx context.Context, stream server.Stream) error {
	m := new(MoverServiceRequestRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.MoverServiceHandler.Request(ctx, m, &moverServiceRequestStream{stream})
}

type MoverService_RequestStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*MoverServiceRequestResponse) error
}

type moverServiceRequestStream struct {
	stream server.Stream
}

func (x *moverServiceRequestStream) Close() error {
	return x.stream.Close()
}

func (x *moverServiceRequestStream) Context() context.Context {
	return x.stream.Context()
}

func (x *moverServiceRequestStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *moverServiceRequestStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *moverServiceRequestStream) Send(m *MoverServiceRequestResponse) error {
	return x.stream.Send(m)
}

func (h *moverServiceHandler) Requests(ctx context.Context, stream server.Stream) error {
	return h.MoverServiceHandler.Requests(ctx, &moverServiceRequestsStream{stream})
}

type MoverService_RequestsStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*MoverServiceRequestsResponse) error
	Recv() (*MoverServiceRequestsRequest, error)
}

type moverServiceRequestsStream struct {
	stream server.Stream
}

func (x *moverServiceRequestsStream) Close() error {
	return x.stream.Close()
}

func (x *moverServiceRequestsStream) Context() context.Context {
	return x.stream.Context()
}

func (x *moverServiceRequestsStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *moverServiceRequestsStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *moverServiceRequestsStream) Send(m *MoverServiceRequestsResponse) error {
	return x.stream.Send(m)
}

func (x *moverServiceRequestsStream) Recv() (*MoverServiceRequestsRequest, error) {
	m := new(MoverServiceRequestsRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
