// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: nodeum/micro/v1/mover.proto

package microv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MoverServiceClient is the client API for MoverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MoverServiceClient interface {
	// Starts a task execution on the mover
	Start(ctx context.Context, in *MoverServiceStartRequest, opts ...grpc.CallOption) (*MoverServiceStartResponse, error)
	// Executes a single request on the mover
	Request(ctx context.Context, in *MoverServiceRequestRequest, opts ...grpc.CallOption) (MoverService_RequestClient, error)
}

type moverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMoverServiceClient(cc grpc.ClientConnInterface) MoverServiceClient {
	return &moverServiceClient{cc}
}

func (c *moverServiceClient) Start(ctx context.Context, in *MoverServiceStartRequest, opts ...grpc.CallOption) (*MoverServiceStartResponse, error) {
	out := new(MoverServiceStartResponse)
	err := c.cc.Invoke(ctx, "/nodeum.micro.v1.MoverService/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moverServiceClient) Request(ctx context.Context, in *MoverServiceRequestRequest, opts ...grpc.CallOption) (MoverService_RequestClient, error) {
	stream, err := c.cc.NewStream(ctx, &MoverService_ServiceDesc.Streams[0], "/nodeum.micro.v1.MoverService/Request", opts...)
	if err != nil {
		return nil, err
	}
	x := &moverServiceRequestClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MoverService_RequestClient interface {
	Recv() (*MoverServiceRequestResponse, error)
	grpc.ClientStream
}

type moverServiceRequestClient struct {
	grpc.ClientStream
}

func (x *moverServiceRequestClient) Recv() (*MoverServiceRequestResponse, error) {
	m := new(MoverServiceRequestResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MoverServiceServer is the server API for MoverService service.
// All implementations must embed UnimplementedMoverServiceServer
// for forward compatibility
type MoverServiceServer interface {
	// Starts a task execution on the mover
	Start(context.Context, *MoverServiceStartRequest) (*MoverServiceStartResponse, error)
	// Executes a single request on the mover
	Request(*MoverServiceRequestRequest, MoverService_RequestServer) error
	mustEmbedUnimplementedMoverServiceServer()
}

// UnimplementedMoverServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMoverServiceServer struct {
}

func (UnimplementedMoverServiceServer) Start(context.Context, *MoverServiceStartRequest) (*MoverServiceStartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedMoverServiceServer) Request(*MoverServiceRequestRequest, MoverService_RequestServer) error {
	return status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedMoverServiceServer) mustEmbedUnimplementedMoverServiceServer() {}

// UnsafeMoverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MoverServiceServer will
// result in compilation errors.
type UnsafeMoverServiceServer interface {
	mustEmbedUnimplementedMoverServiceServer()
}

func RegisterMoverServiceServer(s grpc.ServiceRegistrar, srv MoverServiceServer) {
	s.RegisterService(&MoverService_ServiceDesc, srv)
}

func _MoverService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoverServiceStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoverServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodeum.micro.v1.MoverService/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoverServiceServer).Start(ctx, req.(*MoverServiceStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoverService_Request_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MoverServiceRequestRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MoverServiceServer).Request(m, &moverServiceRequestServer{stream})
}

type MoverService_RequestServer interface {
	Send(*MoverServiceRequestResponse) error
	grpc.ServerStream
}

type moverServiceRequestServer struct {
	grpc.ServerStream
}

func (x *moverServiceRequestServer) Send(m *MoverServiceRequestResponse) error {
	return x.ServerStream.SendMsg(m)
}

// MoverService_ServiceDesc is the grpc.ServiceDesc for MoverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MoverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nodeum.micro.v1.MoverService",
	HandlerType: (*MoverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _MoverService_Start_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Request",
			Handler:       _MoverService_Request_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nodeum/micro/v1/mover.proto",
}
