// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: nodeum/micro/v1/mover.proto

package microv1

import (
	v1 "github.com/nodeum-io/nodeum-proto/nodeum/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Start a new context for receiving requests
type MoverServiceStartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Workflow ID, for logging
	WorkflowId string `protobuf:"bytes,1,opt,name=workflow_id,proto3" json:"workflow_id,omitempty"`
	// Task execution
	Execution *v1.Execution `protobuf:"bytes,4,opt,name=execution,proto3" json:"execution,omitempty"`
	// Optional source of requests
	Source *v1.Storage `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	// Optional destinations of requests
	Destination *v1.Storage `protobuf:"bytes,6,opt,name=destination,proto3" json:"destination,omitempty"`
}

func (x *MoverServiceStartRequest) Reset() {
	*x = MoverServiceStartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeum_micro_v1_mover_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoverServiceStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoverServiceStartRequest) ProtoMessage() {}

func (x *MoverServiceStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeum_micro_v1_mover_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoverServiceStartRequest.ProtoReflect.Descriptor instead.
func (*MoverServiceStartRequest) Descriptor() ([]byte, []int) {
	return file_nodeum_micro_v1_mover_proto_rawDescGZIP(), []int{0}
}

func (x *MoverServiceStartRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *MoverServiceStartRequest) GetExecution() *v1.Execution {
	if x != nil {
		return x.Execution
	}
	return nil
}

func (x *MoverServiceStartRequest) GetSource() *v1.Storage {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *MoverServiceStartRequest) GetDestination() *v1.Storage {
	if x != nil {
		return x.Destination
	}
	return nil
}

type MoverServicePauseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MoverServicePauseRequest) Reset() {
	*x = MoverServicePauseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeum_micro_v1_mover_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoverServicePauseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoverServicePauseRequest) ProtoMessage() {}

func (x *MoverServicePauseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeum_micro_v1_mover_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoverServicePauseRequest.ProtoReflect.Descriptor instead.
func (*MoverServicePauseRequest) Descriptor() ([]byte, []int) {
	return file_nodeum_micro_v1_mover_proto_rawDescGZIP(), []int{1}
}

func (x *MoverServicePauseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MoverServicePauseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// English user-friendly message (eg. "Pause requested")
	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *MoverServicePauseResponse) Reset() {
	*x = MoverServicePauseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeum_micro_v1_mover_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoverServicePauseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoverServicePauseResponse) ProtoMessage() {}

func (x *MoverServicePauseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeum_micro_v1_mover_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoverServicePauseResponse.ProtoReflect.Descriptor instead.
func (*MoverServicePauseResponse) Descriptor() ([]byte, []int) {
	return file_nodeum_micro_v1_mover_proto_rawDescGZIP(), []int{2}
}

func (x *MoverServicePauseResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type MoverServiceResumeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MoverServiceResumeRequest) Reset() {
	*x = MoverServiceResumeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeum_micro_v1_mover_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoverServiceResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoverServiceResumeRequest) ProtoMessage() {}

func (x *MoverServiceResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeum_micro_v1_mover_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoverServiceResumeRequest.ProtoReflect.Descriptor instead.
func (*MoverServiceResumeRequest) Descriptor() ([]byte, []int) {
	return file_nodeum_micro_v1_mover_proto_rawDescGZIP(), []int{3}
}

func (x *MoverServiceResumeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MoverServiceResumeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// English user-friendly message (eg. "Resume requested")
	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *MoverServiceResumeResponse) Reset() {
	*x = MoverServiceResumeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeum_micro_v1_mover_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoverServiceResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoverServiceResumeResponse) ProtoMessage() {}

func (x *MoverServiceResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeum_micro_v1_mover_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoverServiceResumeResponse.ProtoReflect.Descriptor instead.
func (*MoverServiceResumeResponse) Descriptor() ([]byte, []int) {
	return file_nodeum_micro_v1_mover_proto_rawDescGZIP(), []int{4}
}

func (x *MoverServiceResumeResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type MoverServiceStopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MoverServiceStopRequest) Reset() {
	*x = MoverServiceStopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeum_micro_v1_mover_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoverServiceStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoverServiceStopRequest) ProtoMessage() {}

func (x *MoverServiceStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeum_micro_v1_mover_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoverServiceStopRequest.ProtoReflect.Descriptor instead.
func (*MoverServiceStopRequest) Descriptor() ([]byte, []int) {
	return file_nodeum_micro_v1_mover_proto_rawDescGZIP(), []int{5}
}

func (x *MoverServiceStopRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MoverServiceStopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// English user-friendly message (eg. "Stop requested")
	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *MoverServiceStopResponse) Reset() {
	*x = MoverServiceStopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeum_micro_v1_mover_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoverServiceStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoverServiceStopResponse) ProtoMessage() {}

func (x *MoverServiceStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeum_micro_v1_mover_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoverServiceStopResponse.ProtoReflect.Descriptor instead.
func (*MoverServiceStopResponse) Descriptor() ([]byte, []int) {
	return file_nodeum_micro_v1_mover_proto_rawDescGZIP(), []int{6}
}

func (x *MoverServiceStopResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type MoverServiceRequestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *v1.Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *MoverServiceRequestRequest) Reset() {
	*x = MoverServiceRequestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeum_micro_v1_mover_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoverServiceRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoverServiceRequestRequest) ProtoMessage() {}

func (x *MoverServiceRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeum_micro_v1_mover_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoverServiceRequestRequest.ProtoReflect.Descriptor instead.
func (*MoverServiceRequestRequest) Descriptor() ([]byte, []int) {
	return file_nodeum_micro_v1_mover_proto_rawDescGZIP(), []int{7}
}

func (x *MoverServiceRequestRequest) GetRequest() *v1.Request {
	if x != nil {
		return x.Request
	}
	return nil
}

type MoverServiceRequestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *v1.Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *MoverServiceRequestResponse) Reset() {
	*x = MoverServiceRequestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeum_micro_v1_mover_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoverServiceRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoverServiceRequestResponse) ProtoMessage() {}

func (x *MoverServiceRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeum_micro_v1_mover_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoverServiceRequestResponse.ProtoReflect.Descriptor instead.
func (*MoverServiceRequestResponse) Descriptor() ([]byte, []int) {
	return file_nodeum_micro_v1_mover_proto_rawDescGZIP(), []int{8}
}

func (x *MoverServiceRequestResponse) GetResult() *v1.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type MoverServiceRequestsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Action:
	//
	//	*MoverServiceRequestsRequest_Start
	//	*MoverServiceRequestsRequest_Request
	Action isMoverServiceRequestsRequest_Action `protobuf_oneof:"action"`
}

func (x *MoverServiceRequestsRequest) Reset() {
	*x = MoverServiceRequestsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeum_micro_v1_mover_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoverServiceRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoverServiceRequestsRequest) ProtoMessage() {}

func (x *MoverServiceRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeum_micro_v1_mover_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoverServiceRequestsRequest.ProtoReflect.Descriptor instead.
func (*MoverServiceRequestsRequest) Descriptor() ([]byte, []int) {
	return file_nodeum_micro_v1_mover_proto_rawDescGZIP(), []int{9}
}

func (m *MoverServiceRequestsRequest) GetAction() isMoverServiceRequestsRequest_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *MoverServiceRequestsRequest) GetStart() *MoverServiceStartRequest {
	if x, ok := x.GetAction().(*MoverServiceRequestsRequest_Start); ok {
		return x.Start
	}
	return nil
}

func (x *MoverServiceRequestsRequest) GetRequest() *v1.Request {
	if x, ok := x.GetAction().(*MoverServiceRequestsRequest_Request); ok {
		return x.Request
	}
	return nil
}

type isMoverServiceRequestsRequest_Action interface {
	isMoverServiceRequestsRequest_Action()
}

type MoverServiceRequestsRequest_Start struct {
	// Start action, must be called before `request`
	Start *MoverServiceStartRequest `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type MoverServiceRequestsRequest_Request struct {
	Request *v1.Request `protobuf:"bytes,5,opt,name=request,proto3,oneof"`
}

func (*MoverServiceRequestsRequest_Start) isMoverServiceRequestsRequest_Action() {}

func (*MoverServiceRequestsRequest_Request) isMoverServiceRequestsRequest_Action() {}

type MoverServiceRequestsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *v1.Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *MoverServiceRequestsResponse) Reset() {
	*x = MoverServiceRequestsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeum_micro_v1_mover_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoverServiceRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoverServiceRequestsResponse) ProtoMessage() {}

func (x *MoverServiceRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeum_micro_v1_mover_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoverServiceRequestsResponse.ProtoReflect.Descriptor instead.
func (*MoverServiceRequestsResponse) Descriptor() ([]byte, []int) {
	return file_nodeum_micro_v1_mover_proto_rawDescGZIP(), []int{10}
}

func (x *MoverServiceRequestsResponse) GetResult() *v1.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_nodeum_micro_v1_mover_proto protoreflect.FileDescriptor

var file_nodeum_micro_v1_mover_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2f, 0x76,
	0x31, 0x2f, 0x6d, 0x6f, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6e,
	0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x1a, 0x1e,
	0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31,
	0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d,
	0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31,
	0x2f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x6e,
	0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b,
	0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31,
	0x2f, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe7, 0x01, 0x0a, 0x18,
	0x4d, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x77, 0x6f, 0x72, 0x6b,
	0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x77,
	0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x69, 0x64, 0x12, 0x39, 0x0a, 0x09, 0x65, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x65, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2a, 0x0a, 0x18, 0x4d, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x61, 0x75, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x2d, 0x0a, 0x19, 0x4d, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x50, 0x61, 0x75, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x22, 0x2b, 0x0a, 0x19, 0x4d, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2e, 0x0a,
	0x1a, 0x4d, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x29, 0x0a,
	0x17, 0x4d, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x6f,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2c, 0x0a, 0x18, 0x4d, 0x6f, 0x76, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x51, 0x0a, 0x1a, 0x4d, 0x6f, 0x76, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4f, 0x0a, 0x1b, 0x4d, 0x6f, 0x76,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x75,
	0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0xa1, 0x01, 0x0a, 0x1b, 0x4d,
	0x6f, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x41, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6e, 0x6f, 0x64, 0x65,
	0x75, 0x6d, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x76, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x35, 0x0a,
	0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x07, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x50,
	0x0a, 0x1c, 0x4d, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x32, 0x89, 0x04, 0x0a, 0x0c, 0x4d, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x60, 0x0a, 0x05, 0x50, 0x61, 0x75, 0x73, 0x65, 0x12, 0x29, 0x2e, 0x6e, 0x6f, 0x64,
	0x65, 0x75, 0x6d, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x76,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x61, 0x75, 0x73, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x6d,
	0x69, 0x63, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x50, 0x61, 0x75, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x63, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x12, 0x2a, 0x2e,
	0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x4d, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x6e, 0x6f, 0x64, 0x65,
	0x75, 0x6d, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x76, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70,
	0x12, 0x28, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e,
	0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53,
	0x74, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x6e, 0x6f, 0x64,
	0x65, 0x75, 0x6d, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x76,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x66, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2b, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x6d, 0x69, 0x63, 0x72,
	0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2c, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x76,
	0x31, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12,
	0x6b, 0x0a, 0x08, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x2c, 0x2e, 0x6e, 0x6f,
	0x64, 0x65, 0x75, 0x6d, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f,
	0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x6e, 0x6f, 0x64, 0x65,
	0x75, 0x6d, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x76, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x3b, 0x5a, 0x39,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x75,
	0x6d, 0x2d, 0x69, 0x6f, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2d, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x75, 0x6d, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2f, 0x76,
	0x31, 0x3b, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_nodeum_micro_v1_mover_proto_rawDescOnce sync.Once
	file_nodeum_micro_v1_mover_proto_rawDescData = file_nodeum_micro_v1_mover_proto_rawDesc
)

func file_nodeum_micro_v1_mover_proto_rawDescGZIP() []byte {
	file_nodeum_micro_v1_mover_proto_rawDescOnce.Do(func() {
		file_nodeum_micro_v1_mover_proto_rawDescData = protoimpl.X.CompressGZIP(file_nodeum_micro_v1_mover_proto_rawDescData)
	})
	return file_nodeum_micro_v1_mover_proto_rawDescData
}

var file_nodeum_micro_v1_mover_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_nodeum_micro_v1_mover_proto_goTypes = []interface{}{
	(*MoverServiceStartRequest)(nil),     // 0: nodeum.micro.v1.MoverServiceStartRequest
	(*MoverServicePauseRequest)(nil),     // 1: nodeum.micro.v1.MoverServicePauseRequest
	(*MoverServicePauseResponse)(nil),    // 2: nodeum.micro.v1.MoverServicePauseResponse
	(*MoverServiceResumeRequest)(nil),    // 3: nodeum.micro.v1.MoverServiceResumeRequest
	(*MoverServiceResumeResponse)(nil),   // 4: nodeum.micro.v1.MoverServiceResumeResponse
	(*MoverServiceStopRequest)(nil),      // 5: nodeum.micro.v1.MoverServiceStopRequest
	(*MoverServiceStopResponse)(nil),     // 6: nodeum.micro.v1.MoverServiceStopResponse
	(*MoverServiceRequestRequest)(nil),   // 7: nodeum.micro.v1.MoverServiceRequestRequest
	(*MoverServiceRequestResponse)(nil),  // 8: nodeum.micro.v1.MoverServiceRequestResponse
	(*MoverServiceRequestsRequest)(nil),  // 9: nodeum.micro.v1.MoverServiceRequestsRequest
	(*MoverServiceRequestsResponse)(nil), // 10: nodeum.micro.v1.MoverServiceRequestsResponse
	(*v1.Execution)(nil),                 // 11: nodeum.common.v1.Execution
	(*v1.Storage)(nil),                   // 12: nodeum.common.v1.Storage
	(*v1.Request)(nil),                   // 13: nodeum.common.v1.Request
	(*v1.Result)(nil),                    // 14: nodeum.common.v1.Result
}
var file_nodeum_micro_v1_mover_proto_depIdxs = []int32{
	11, // 0: nodeum.micro.v1.MoverServiceStartRequest.execution:type_name -> nodeum.common.v1.Execution
	12, // 1: nodeum.micro.v1.MoverServiceStartRequest.source:type_name -> nodeum.common.v1.Storage
	12, // 2: nodeum.micro.v1.MoverServiceStartRequest.destination:type_name -> nodeum.common.v1.Storage
	13, // 3: nodeum.micro.v1.MoverServiceRequestRequest.request:type_name -> nodeum.common.v1.Request
	14, // 4: nodeum.micro.v1.MoverServiceRequestResponse.result:type_name -> nodeum.common.v1.Result
	0,  // 5: nodeum.micro.v1.MoverServiceRequestsRequest.start:type_name -> nodeum.micro.v1.MoverServiceStartRequest
	13, // 6: nodeum.micro.v1.MoverServiceRequestsRequest.request:type_name -> nodeum.common.v1.Request
	14, // 7: nodeum.micro.v1.MoverServiceRequestsResponse.result:type_name -> nodeum.common.v1.Result
	1,  // 8: nodeum.micro.v1.MoverService.Pause:input_type -> nodeum.micro.v1.MoverServicePauseRequest
	3,  // 9: nodeum.micro.v1.MoverService.Resume:input_type -> nodeum.micro.v1.MoverServiceResumeRequest
	5,  // 10: nodeum.micro.v1.MoverService.Stop:input_type -> nodeum.micro.v1.MoverServiceStopRequest
	7,  // 11: nodeum.micro.v1.MoverService.Request:input_type -> nodeum.micro.v1.MoverServiceRequestRequest
	9,  // 12: nodeum.micro.v1.MoverService.Requests:input_type -> nodeum.micro.v1.MoverServiceRequestsRequest
	2,  // 13: nodeum.micro.v1.MoverService.Pause:output_type -> nodeum.micro.v1.MoverServicePauseResponse
	4,  // 14: nodeum.micro.v1.MoverService.Resume:output_type -> nodeum.micro.v1.MoverServiceResumeResponse
	6,  // 15: nodeum.micro.v1.MoverService.Stop:output_type -> nodeum.micro.v1.MoverServiceStopResponse
	8,  // 16: nodeum.micro.v1.MoverService.Request:output_type -> nodeum.micro.v1.MoverServiceRequestResponse
	10, // 17: nodeum.micro.v1.MoverService.Requests:output_type -> nodeum.micro.v1.MoverServiceRequestsResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_nodeum_micro_v1_mover_proto_init() }
func file_nodeum_micro_v1_mover_proto_init() {
	if File_nodeum_micro_v1_mover_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nodeum_micro_v1_mover_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoverServiceStartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeum_micro_v1_mover_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoverServicePauseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeum_micro_v1_mover_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoverServicePauseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeum_micro_v1_mover_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoverServiceResumeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeum_micro_v1_mover_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoverServiceResumeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeum_micro_v1_mover_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoverServiceStopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeum_micro_v1_mover_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoverServiceStopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeum_micro_v1_mover_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoverServiceRequestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeum_micro_v1_mover_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoverServiceRequestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeum_micro_v1_mover_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoverServiceRequestsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeum_micro_v1_mover_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoverServiceRequestsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_nodeum_micro_v1_mover_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*MoverServiceRequestsRequest_Start)(nil),
		(*MoverServiceRequestsRequest_Request)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nodeum_micro_v1_mover_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nodeum_micro_v1_mover_proto_goTypes,
		DependencyIndexes: file_nodeum_micro_v1_mover_proto_depIdxs,
		MessageInfos:      file_nodeum_micro_v1_mover_proto_msgTypes,
	}.Build()
	File_nodeum_micro_v1_mover_proto = out.File
	file_nodeum_micro_v1_mover_proto_rawDesc = nil
	file_nodeum_micro_v1_mover_proto_goTypes = nil
	file_nodeum_micro_v1_mover_proto_depIdxs = nil
}
