// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: nodeum/micro/v1/mover.proto

package microv1

import (
	fmt "fmt"
	_ "github.com/nodeum-io/nodeum-proto/nodeum/common/v1"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for MoverService service

func NewMoverServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for MoverService service

type MoverService interface {
	Start(ctx context.Context, in *MoverServiceStartRequest, opts ...client.CallOption) (*MoverServiceStartResponse, error)
}

type moverService struct {
	c    client.Client
	name string
}

func NewMoverService(name string, c client.Client) MoverService {
	return &moverService{
		c:    c,
		name: name,
	}
}

func (c *moverService) Start(ctx context.Context, in *MoverServiceStartRequest, opts ...client.CallOption) (*MoverServiceStartResponse, error) {
	req := c.c.NewRequest(c.name, "MoverService.Start", in)
	out := new(MoverServiceStartResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MoverService service

type MoverServiceHandler interface {
	Start(context.Context, *MoverServiceStartRequest, *MoverServiceStartResponse) error
}

func RegisterMoverServiceHandler(s server.Server, hdlr MoverServiceHandler, opts ...server.HandlerOption) error {
	type moverService interface {
		Start(ctx context.Context, in *MoverServiceStartRequest, out *MoverServiceStartResponse) error
	}
	type MoverService struct {
		moverService
	}
	h := &moverServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&MoverService{h}, opts...))
}

type moverServiceHandler struct {
	MoverServiceHandler
}

func (h *moverServiceHandler) Start(ctx context.Context, in *MoverServiceStartRequest, out *MoverServiceStartResponse) error {
	return h.MoverServiceHandler.Start(ctx, in, out)
}
