// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: protobuf/dispatcher.micro.proto

package dispatcherpb

import (
	fmt "fmt"
	_ "github.com/nodeum-io/nodeum-plugins/protobuf/types/taskpb"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	proto "google.golang.org/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/structpb"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Dispatcher service

func NewDispatcherEndpoints() []*api.Endpoint {
	return []*api.Endpoint{
		{
			Name:    "Dispatcher.Start",
			Path:    []string{"/task/start"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "Dispatcher.Pause",
			Path:    []string{"/task/pause/{id}"},
			Method:  []string{"POST"},
			Body:    "",
			Handler: "rpc",
		},
		{
			Name:    "Dispatcher.Resume",
			Path:    []string{"/task/resume/{id}"},
			Method:  []string{"POST"},
			Body:    "",
			Handler: "rpc",
		},
		{
			Name:    "Dispatcher.Stop",
			Path:    []string{"/task/stop/{id}"},
			Method:  []string{"POST"},
			Body:    "",
			Handler: "rpc",
		},
	}
}

// Client API for Dispatcher service

type DispatcherService interface {
	Start(ctx context.Context, in *StartRequest, opts ...client.CallOption) (*StartResponse, error)
	Pause(ctx context.Context, in *TriggerRequest, opts ...client.CallOption) (*TriggerResponse, error)
	Resume(ctx context.Context, in *TriggerRequest, opts ...client.CallOption) (*TriggerResponse, error)
	Stop(ctx context.Context, in *TriggerRequest, opts ...client.CallOption) (*TriggerResponse, error)
}

type dispatcherService struct {
	c    client.Client
	name string
}

func NewDispatcherService(name string, c client.Client) DispatcherService {
	return &dispatcherService{
		c:    c,
		name: name,
	}
}

func (c *dispatcherService) Start(ctx context.Context, in *StartRequest, opts ...client.CallOption) (*StartResponse, error) {
	req := c.c.NewRequest(c.name, "Dispatcher.Start", in)
	out := new(StartResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatcherService) Pause(ctx context.Context, in *TriggerRequest, opts ...client.CallOption) (*TriggerResponse, error) {
	req := c.c.NewRequest(c.name, "Dispatcher.Pause", in)
	out := new(TriggerResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatcherService) Resume(ctx context.Context, in *TriggerRequest, opts ...client.CallOption) (*TriggerResponse, error) {
	req := c.c.NewRequest(c.name, "Dispatcher.Resume", in)
	out := new(TriggerResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatcherService) Stop(ctx context.Context, in *TriggerRequest, opts ...client.CallOption) (*TriggerResponse, error) {
	req := c.c.NewRequest(c.name, "Dispatcher.Stop", in)
	out := new(TriggerResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Dispatcher service

type DispatcherHandler interface {
	Start(context.Context, *StartRequest, *StartResponse) error
	Pause(context.Context, *TriggerRequest, *TriggerResponse) error
	Resume(context.Context, *TriggerRequest, *TriggerResponse) error
	Stop(context.Context, *TriggerRequest, *TriggerResponse) error
}

func RegisterDispatcherHandler(s server.Server, hdlr DispatcherHandler, opts ...server.HandlerOption) error {
	type dispatcher interface {
		Start(ctx context.Context, in *StartRequest, out *StartResponse) error
		Pause(ctx context.Context, in *TriggerRequest, out *TriggerResponse) error
		Resume(ctx context.Context, in *TriggerRequest, out *TriggerResponse) error
		Stop(ctx context.Context, in *TriggerRequest, out *TriggerResponse) error
	}
	type Dispatcher struct {
		dispatcher
	}
	h := &dispatcherHandler{hdlr}
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "Dispatcher.Start",
		Path:    []string{"/task/start"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "Dispatcher.Pause",
		Path:    []string{"/task/pause/{id}"},
		Method:  []string{"POST"},
		Body:    "",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "Dispatcher.Resume",
		Path:    []string{"/task/resume/{id}"},
		Method:  []string{"POST"},
		Body:    "",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "Dispatcher.Stop",
		Path:    []string{"/task/stop/{id}"},
		Method:  []string{"POST"},
		Body:    "",
		Handler: "rpc",
	}))
	return s.Handle(s.NewHandler(&Dispatcher{h}, opts...))
}

type dispatcherHandler struct {
	DispatcherHandler
}

func (h *dispatcherHandler) Start(ctx context.Context, in *StartRequest, out *StartResponse) error {
	return h.DispatcherHandler.Start(ctx, in, out)
}

func (h *dispatcherHandler) Pause(ctx context.Context, in *TriggerRequest, out *TriggerResponse) error {
	return h.DispatcherHandler.Pause(ctx, in, out)
}

func (h *dispatcherHandler) Resume(ctx context.Context, in *TriggerRequest, out *TriggerResponse) error {
	return h.DispatcherHandler.Resume(ctx, in, out)
}

func (h *dispatcherHandler) Stop(ctx context.Context, in *TriggerRequest, out *TriggerResponse) error {
	return h.DispatcherHandler.Stop(ctx, in, out)
}
